version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile  # optional if Dockerfile is named 'Dockerfile'
    ports:
      - "8080:80"
    container_name: apache_web
    restart: unless-stopped
